### ISSUE TITLE
59.com.tr

### ISSUE THREAD

**Issue by azgard121** [azgard121/hell#4]
http://www.59.com.tr/emlak

**Comment by azgard121** [comment]
Нужно проверить (2016-08-17 10:55:08)

**Comment by azgard121** [comment]
Выложили (2016-08-17 12:52:37)

**Comment by azgard121** [comment]
Новый.
 (2016-09-21 15:34:25)

**Comment by azgard121** [comment]
stas (2016-09-21 15:34:29)

**Comment by azgard121** [comment]
Нужно проверить.
 (2016-09-21 15:34:36)

**Comment by azgard121** [comment]
None: Новый.
propiedades.emol.com config is broken.
BrokenConfigError("Field "text" is getting diffs all the time, stats:\ntext: 500/500\nsection: 0/500\narea_total: 32/500\nheader: 0/500\nroom_count: 1/479\nimages: 493/500\ngeo: 8/500\nprice: 499/500",)
Traceback (most recent call last):
  File "/usr/share/polaris/downloader/downloader/tasks.py", line 151, in download
    diff, data = site_downloader.download_page(page_id)
  File "/usr/share/polaris/downloader/downloader/downloader.py", line 82, in download_page
    "Field "%s" is getting diffs all the time, stats:\n%s" % (exc.field, self.stats)
BrokenConfigError: Field "text" is getting diffs all the time, stats:
text: 500/500
section: 0/500
area_total: 32/500
header: 0/500
room_count: 1/479
images: 493/500
geo: 8/500
price: 499/500
 (2016-12-14 15:04:46)

**Comment by azgard121** [comment]
server: Новый.
propiedades.emol.com config is broken.
BrokenConfigError("Field "text" is getting diffs all the time, stats:\ntext: 500/500\nsection: 0/500\narea_total: 32/500\nheader: 0/500\nroom_count: 1/479\nimages: 493/500\ngeo: 8/500\nprice: 499/500",)
```Traceback (most recent call last):
  File "/usr/share/polaris/downloader/downloader/tasks.py", line 151, in download
    diff, data = site_downloader.download_page(page_id)
  File "/usr/share/polaris/downloader/downloader/downloader.py", line 82, in download_page
    "Field "%s" is getting diffs all the time, stats:\n%s" % (exc.field, self.stats)
BrokenConfigError: Field "text" is getting diffs all the time, stats:
text: 500/500
section: 0/500
area_total: 32/500
header: 0/500
room_count: 1/479
images: 493/500
geo: 8/500
price: 499/500
``` (2016-12-14 15:30:34)

**Comment by azgard121** [comment]
server: Новый.
propiedades.emol.com config is broken.
BrokenConfigError("Field "text" is getting diffs all the time, stats:\ntext: 500/500\nsection: 0/500\narea_total: 32/500\nheader: 0/500\nroom_count: 1/479\nimages: 493/500\ngeo: 8/500\nprice: 499/500",)
```Traceback (most recent call last):
  File "/usr/share/polaris/downloader/downloader/tasks.py", line 151, in download
    diff, data = site_downloader.download_page(page_id)
  File "/usr/share/polaris/downloader/downloader/downloader.py", line 82, in download_page
    "Field "%s" is getting diffs all the time, stats:\n%s" % (exc.field, self.stats)
BrokenConfigError: Field "text" is getting diffs all the time, stats:
text: 500/500
section: 0/500
area_total: 32/500
header: 0/500
room_count: 1/479
images: 493/500
geo: 8/500
price: 499/500
``` (2016-12-14 16:21:06)

**Comment by azgard121** [comment]
None: Переоткрыть.
test reopen (2017-07-05 11:58:44)

**Comment by azgard121** [comment]
None: Переоткрыть.
test reopen (2017-07-05 12:52:08)

**Comment by azgard121** [comment]
None: Переоткрыть.
test reopen (2017-07-05 14:09:57)

**Comment by azgard121** [comment]
Stanislav Borovyk: Переоткрыть.
reopen import (2017-09-21 16:48:54)

**Comment by azgard121** [comment]
Stanislav Borovyk поставил на Stanislav Borovyk (2017-09-21 16:49:31)

**Comment by azgard121** [comment]
Stanislav Borovyk: Нужно проверить.
received (2017-09-21 16:50:56)

**Comment by azgard121** [comment]
Stanislav Borovyk: Нужно выложить.
working (2017-09-21 16:51:36)

**Comment by azgard121** [comment]
Stanislav Borovyk: Не берем.
test (2017-09-21 19:34:17)

**Comment by azgard121** [comment]
Stanislav Borovyk: Переоткрыть.
 (2017-09-21 19:44:33)

**Comment by azgard121** [comment]
Stanislav Borovyk: Не берем.
test trigger (2017-09-21 19:48:07)

**Comment by azgard121** [comment]
Stanislav Borovyk: Переоткрыть.
 (2017-09-21 19:49:25)

**Comment by azgard121** [comment]
Stanislav Borovyk: Переоткрыть.
test reopen import (2017-09-26 12:05:37)

**Comment by azgard121** [comment]
server: Переоткрыть.
59.com.tr config is broken.
463 Client Error:  for url: https://www.test.com/ (2017-09-26 15:51:24)

**Comment by azgard121** [comment]
Stanislav Borovyk: Нужно проверить.
 (2017-10-02 15:40:22)

**Comment by azgard121** [comment]
Stanislav Borovyk: Выложили.
 (2017-10-02 15:40:27)

**Comment by azgard121** [comment]
Stanislav Borovyk: Переоткрыть.
 (2017-10-02 15:42:17)

**Comment by azgard121** [comment]
Stanislav Borovyk: Нужно проверить.
 (2017-10-02 15:44:06)

**Comment by azgard121** [comment]
Stanislav Borovyk: Выложили.
 (2017-10-02 15:44:11)

**Comment by azgard121** [comment]
Stanislav Borovyk: Переоткрыть.
 (2017-10-03 17:18:20)

**Comment by azgard121** [comment]
Stanislav Borovyk: Нужно проверить.
 (2017-10-03 17:38:13)

**Comment by azgard121** [comment]
Stanislav Borovyk: Выложили.
 (2017-10-03 17:38:18)

**Comment by azgard121** [comment]
Stanislav Borovyk: Переоткрыть.
 (2017-10-04 19:37:35)

**Comment by azgard121** [comment]
None: Нужно проверить.
 (2017-11-02 18:21:49)

**Comment by azgard121** [comment]
None: Нужно выложить.
 (2017-11-02 18:22:03)

**Comment by azgard121** [comment]
None: Выложили.
 (2017-11-02 18:22:06)

**Comment by azgard121** [comment]
None: Переоткрыть.
 (2017-11-02 18:22:22)

**Comment by azgard121** [comment]
None поставил на Stanislav Borovyk (2017-11-02 18:22:22)

**Comment by azgard121** [comment]
None: Редизайн.
 (2017-11-02 18:22:36)

**Comment by azgard121** [comment]
None: Нужно проверить.
 (2017-11-02 18:22:44)

**Comment by azgard121** [comment]
None: Нужно выложить.
 (2017-11-02 18:22:54)

**Comment by azgard121** [comment]
None: Переоткрыть.
 (2017-11-02 18:23:08)

**Comment by azgard121** [comment]
None поставил на Stanislav Borovyk (2017-11-02 18:23:09)

**Comment by azgard121** [comment]
None: Нужно проверить.
 (2017-11-02 18:23:19)

**Comment by azgard121** [comment]
None: Нужно выложить.
 (2017-11-02 18:23:30)

**Comment by azgard121** [comment]
None: Выложили.
 (2017-11-02 18:23:33)

**Comment by azgard121** [comment]
None: Переоткрыть.
 (2017-11-02 18:30:49)

**Comment by azgard121** [comment]
None поставил на Stanislav Borovyk (2017-11-02 18:30:50)

**Comment by azgard121** [comment]
None: Редизайн.
 (2017-11-02 18:31:04)

**Comment by azgard121** [comment]
None: Нужно проверить.
 (2017-11-02 18:31:18)

**Comment by azgard121** [comment]
None: Переоткрыть.
 (2017-11-02 18:31:31)

**Comment by azgard121** [comment]
None поставил на Stanislav Borovyk (2017-11-02 18:31:33)

**Comment by azgard121** [comment]
None: Нужно проверить.
 (2017-11-02 18:33:24)

**Comment by azgard121** [comment]
None: Нужно выложить.
 (2017-11-02 18:33:42)

**Comment by azgard121** [comment]
None: Выложили.
 (2017-11-02 18:33:48)

**Comment by azgard121** [comment]
None: Переоткрыть.
 (2017-11-02 18:35:16)

**Comment by azgard121** [comment]
None поставил на Stanislav Borovyk (2017-11-02 18:35:18)

**Comment by azgard121** [comment]
None: Редизайн.
 (2017-11-02 18:35:30)

**Comment by azgard121** [comment]
None: Нужно проверить.
 (2017-11-02 18:35:46)

**Comment by azgard121** [comment]
None: Нужно выложить.
 (2017-11-02 18:35:54)

**Comment by azgard121** [comment]
None: Выложили.
 (2017-11-02 18:36:06)

**Comment by azgard121** [comment]
None: Переоткрыть.
 (2017-11-02 18:36:25)

**Comment by azgard121** [comment]
None поставил на Stanislav Borovyk (2017-11-02 18:36:26)

**Comment by azgard121** [comment]
None: Редизайн.
 (2017-11-02 18:36:39)

**Comment by azgard121** [comment]
None: Нужно проверить.
 (2017-11-02 18:36:48)

**Comment by azgard121** [comment]
None: Переоткрыть.
 (2017-11-02 18:37:14)

**Comment by azgard121** [comment]
None поставил на Stanislav Borovyk (2017-11-02 18:37:15)

**Comment by azgard121** [comment]
None: Нужно проверить.
 (2017-11-02 18:37:23)

**Comment by azgard121** [comment]
None: Нужно выложить.
 (2017-11-02 18:37:32)

**Comment by azgard121** [comment]
None: Выложили.
 (2017-11-02 18:37:43)
